openapi: 3.0.3
info:
  title: MultiClip API
  version: 0.1.0
servers:
  - url: https://multiclip-api.onrender.com
paths:
  /health:
    get:
      summary: Liveness probe
      responses:
        '200':
          description: OK
  /api/parse:
    post:
      summary: 입력 URL 메타 파싱 (yt-dlp -j)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url: { type: string }
      responses:
        '200':
          description: Parsed
          content:
            application/json:
              schema:
                type: object
                properties:
                  platform: { type: string }
                  resourceId: { type: string }
                  title: { type: string }
  /api/download:
    post:
      summary: 다운로드 작업 생성 (yt-dlp → S3 업로드)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url: { type: string }
                quality: { type: string, example: "720p" }
                type: { type: string, enum: [video, audio] }
      responses:
        '200':
          description: Job enqueued
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId: { type: string }
  /api/download/status:
    get:
      summary: 작업 상태 조회
      parameters:
        - in: query
          name: jobId
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, enum: [queued, processing, done, error] }
                  progress: { type: integer }
                  downloadUrl: { type: string }
                  error: { type: string }
